import React from 'react';
import classes from './Main.module.css';
import Button from './elements/Button';


function Main(){
    return(
        <div>
            
            <div className={classes.titlecontainer}>
                <div className={classes.banner1}></div>
                <div className={classes.sitetitle}>
                    <h1> Better future</h1> 
                    <p>A carbon footprint is the total amount of greenhouse gases (including carbon dioxide and methane) that are generated by our actions.
                        To have the best chance of avoiding a 2℃ rise in global temperatures, the average global carbon footprint per year needs to drop under 2 tons by 2050.</p>
                    <p>Lowering individual carbon footprints doesn’t happen overnight! By making small changes to our actions, we can start making a big difference.</p> 
                    <div className={ classes.sitetitlebuttons }>
                        <Button link={"/side"} title="Next to Footprint" className={classes.button}/>
                        <Button link={"/side"} title="Next to Footprint" className={classes.button}/>
                    </div> 
                </div>
            </div>
            
            <div className={classes.line}></div>

            <div className={classes.banner}>
                <div className={classes.container}>
                    <h1 className={classes.bannertitle}> Some title come  here</h1>    
                    <div className={classes.cardcontainer}>
                        <div className={classes.card}>
                            <h2>title</h2>
                        </div>
                        <div className={classes.card}>
                            <h2>title</h2>
                        </div>
                        <div className={classes.card}>
                            <h2>title</h2>
                        </div>
                    </div>
                </div>
            </div> 
            <div className={classes.container}>
                <h1 className={classes.title}> Some title come  here</h1>    
                <div className={classes.cardcontainer}>
                    <div className={classes.card}>
                        <h2>title</h2>
                    </div>
                    <div className={classes.card}>
                        <h2>title</h2>
                    </div>
                    <div className={classes.card}>
                        <h2>title</h2>
                    </div>
                </div>
                <Button link={"/side"} title="Next to Footprint" className={classes.button}/>

            </div>
            
            
        </div>
       
    )
}

export default Main;